parameters:
#    lks_man_power.example.class: Lks\ManPowerBundle\Example

services:
#    lks_man_power.example:
#        class: %lks_man_power.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
