parameters:
    lks_man_power_member.class: Lks\ManPowerBundle\Service\MemberService
    lks_man_power_member_dao.class: Lks\ManPowerBundle\Dao\MemberDao
    lks_man_power_project.class: Lks\ManPowerBundle\Service\ProjectService
    lks_man_power_project_dao.class: Lks\ManPowerBundle\Dao\ProjectDao
    date_utility.class: Lks\ManPowerBundle\Utility\DateUtility

services:
    memberService:
        class: %lks_man_power_member.class%
        arguments: [@memberDao]
    memberDao:
        class: %lks_man_power_member_dao.class%
        arguments: [@doctrine.orm.entity_manager]
    projectDao:
        class: %lks_man_power_project_dao.class%
        arguments: [@doctrine.orm.entity_manager]
    projectService:
        class: %lks_man_power_project.class%
        arguments: [@memberService, @projectDao, @logger]
    dateUtility:
        class: %date_utility.class%
