Lks\ManPowerBundle\Entity\om\BaseMember:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        firstname:
            expose: true
        lastname:
            expose: true